/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package badmintonSystem;

// required imports
import com.mysql.jdbc.Connection;
import javax.swing.JFrame;

/**
 *
 * @author Neka
 */
public class chooseConnection extends javax.swing.JFrame {
    
    // declaration of the connection
    static Connection con;
    
    // instantiation of a message dialog
    msgDialog msgDlg = new msgDialog(new javax.swing.JFrame(),true);

    /**
     * Creates new form badmintonLogin
     */
    public chooseConnection() {
        initComponents();
        this.setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JToggleButton();
        btnConfirm = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        conCombo = new javax.swing.JComboBox<>();
        btnTestCon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClubBADMINTON");
        setBounds(new java.awt.Rectangle(0, 23, 0, 0));
        setPreferredSize(new java.awt.Dimension(689, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        usernameLabel.setFont(new java.awt.Font("Adobe Gothic Std", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("CHOOSE CONNECTION TO USE:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemIcons/badmintonLogoTransparent.png"))); // NOI18N

        btnExit.setBackground(new java.awt.Color(255, 0, 51));
        btnExit.setFont(new java.awt.Font("Adobe Gothic Std", 0, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.setAlignmentY(0.0F);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnConfirm.setBackground(new java.awt.Color(0, 153, 102));
        btnConfirm.setFont(new java.awt.Font("Adobe Gothic Std", 0, 13)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Adobe Gothic Std", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLUB BADMINTON ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        conCombo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        conCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "local connection", "college connection" }));
        conCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conComboActionPerformed(evt);
            }
        });

        btnTestCon.setBackground(new java.awt.Color(0, 153, 102));
        btnTestCon.setFont(new java.awt.Font("Adobe Gothic Std", 0, 13)); // NOI18N
        btnTestCon.setForeground(new java.awt.Color(255, 255, 255));
        btnTestCon.setText("TEST CONNECTION");
        btnTestCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTestCon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(conCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnTestCon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // function to select the connection
    private String selectConnection() {
        // initial assignements to set each of the connection's data as null
        String conURL = null ;
        String conUsername = null;
        String conPassword = null;
        
        // defensive programming, form of validation (program cannot go further with a blank input)
        String conChosen = (String)conCombo.getSelectedItem();
        if (conChosen == null) {
            msgDlg.setMessage("No connection chosen, select one");
            msgDlg.setVisible(true);            
        }
        
        // LOCAL CONNECTION: ("jdbc:mysql://localhost:3306/badmintonSchema?useSSL=false", "root", "root18");
        // COLLEGE CONNECTION: ("jdbc:mysql://mysql:3306/badmintonSchema?useSSL=false","student_ntoni","woking18");
        
        // if the connection chosen is local, then set the parameters as the details of the local mySQL workbench
        if (conChosen.equals("local connection")) 
        {
           conURL = "jdbc:mysql://localhost:3306/badmintonSchema?useSSL=false&allowMultiQueries=true"; 
           conUsername = "root";
           conPassword = "root18"; 
           SQLConnection.updateConnectionDetails(conURL, conUsername, conPassword);
        } 
        // if the connection chosen is college, then set the parameters as the details of the college mySQL workbench
        if (conChosen.equals("college connection")) {
           conURL = "jdbc:mysql://mysql:3306/badmintonSchema?useSSL=false&allowMultiQueries=true"; 
           conUsername = "student_ntoni";
           conPassword = "woking18"; 
           SQLConnection.updateConnectionDetails(conURL, conUsername, conPassword);
        } 
        // return the connection that was chosen
       return conChosen; 
    }

    // procedure to open the login form and close this form
    private void openLogin() {
        badmintonLogin bLogin = new badmintonLogin();
        bLogin.setVisible(true);
        bLogin.pack();
        bLogin.setLocationRelativeTo(null);
        bLogin.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose(); 
    }
    
    // event for if the confirm button was clicked
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // boolean value to indicate of the connection exists
        boolean conExists = false; 
        // returns the connection chosen
        String conChosen = selectConnection();     
        
        // test the connection, call the function in the class, SQLConnection, to return the connection
        con = SQLConnection.getConnection();
        // if the connection returned was not null, then a connection exists
        if (con != null) {
            // console log to check if the parameters were received
            System.out.println("CONNECTION CHOSEN: " + conChosen);
            System.out.println("CONNECTION URL: " + SQLConnection.getConnectionURL());
            System.out.println("CONNECTION USERNAME: " + SQLConnection.getConnectionUsername());
            System.out.println("CONNECTION PASSWORD: " + SQLConnection.getConnectionPassword());
            conExists = true;
        }
        
        // open login form if the connection exists
        if (conExists) { 
            openLogin();    
        }       
    }//GEN-LAST:event_btnConfirmActionPerformed
    
    // event for if the exit button was clicked
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // end the current session if there was any running
        SessionManager.endCurrentSession();
        // exit the system
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void conComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conComboActionPerformed
    
    // event for if the test connection button was clicked
    private void btnTestConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestConActionPerformed
        // returns the connection chosen
        String conChosen = selectConnection();
        // console log
        System.out.println("TESTING CONNECTION: " + conChosen + " ...");
        
        // test the connection to check if the connection returned was null or not.
        con = SQLConnection.getConnection();
        // validation to check the connection was not null
        if (con != null) {
            // message dialog to inform the user the connection works
            msgDlg.setMessage("Successful connection");
            msgDlg.setVisible(true);
        }
    }//GEN-LAST:event_btnTestConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseConnection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JButton btnTestCon;
    private javax.swing.JComboBox<String> conCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
